#!/usr/bin/env ruby

# With special thanks to:
# => https://github.com/jm3/dotfiles

class Dotfiles

  def initialize(path)
    @path = path
  end

  def install
    pre_install_check

    if File.directory?(File.join(@path, '.git'))
      pull_repo
    else
      clone_repo
    end
  end

  def run
    `#{File.join(@path, 'tapas')} --debug`
  end

  private

  def pre_install_check
    unless git_installed?
      puts 'Git not found. Exiting installation script.'
      exit
    end
  end

  def git_installed?
    `which git`
    ($?.to_i == 256) ? false : true
  end

  def pull_repo
    Dir.chdir(@path)
    `git pull`
  end

  def clone_repo
    `mkdir -p "#{@path}"`

    puts 'Serving Mac tapas...'
    puts `git clone https://github.com/JeanMertz/mac-tapas.git #{@path}`
  end
end

tapas_path = File.expand_path(File.join('~', '.tapas'))

dotfiles = Dotfiles.new(tapas_path)
dotfiles.install
dotfiles.run
